# Generated by Django 4.2.3 on 2023-07-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingStar',
            new_name='TopReating',
        ),
        migrations.AlterModelOptions(
            name='topreating',
            options={'verbose_name': 'Топ рейтинга', 'verbose_name_plural': 'Топы рейтинга'},
        ),
    ]
