# Generated by Django 4.2.3 on 2023-07-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buster', '0002_rename_ratingstar_topreating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buster.games', verbose_name='игра'),
        ),
    ]
